# Generated by Django 4.1.5 on 2023-03-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_order_details_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_details',
        ),
    ]
