# Generated by Django 4.1.5 on 2023-03-14 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_order_details_order_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, default=False, null=True)),
                ('closed', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='order_details',
            options={'verbose_name': 'Order details', 'verbose_name_plural': 'Orders details'},
        ),
        migrations.CreateModel(
            name='Arrival_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=1, null=True)),
                ('arrival', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.arrival')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.product')),
            ],
            options={
                'verbose_name': 'Arrival details',
                'verbose_name_plural': 'Arrivals details',
            },
        ),
        migrations.AddField(
            model_name='arrival',
            name='products',
            field=models.ManyToManyField(related_name='arrivals', through='back.Arrival_details', to='back.product'),
        ),
    ]
