# Generated by Django 4.1.5 on 2023-03-14 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_arrival_alter_order_details_options_arrival_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('payed_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(default='CASH', max_length=30)),
                ('details', models.TextField(blank=True, max_length=255, null=True)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='back.order')),
            ],
        ),
    ]
