# Generated by Django 4.1.5 on 2023-03-15 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('back', '0014_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('coupon_type', models.CharField(blank=True, default='Percent', max_length=20, null=True)),
                ('discount', models.IntegerField(default=1, null=True)),
                ('max_usage', models.SmallIntegerField(default=1, null=True)),
                ('validity', models.DateTimeField()),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('question', models.TextField(max_length=255)),
                ('answer', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payed_at', 'reference']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='myauth.customer'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='back.product')),
            ],
            options={
                'ordering': ['-created_at', '-rate'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('liked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.product')),
            ],
            options={
                'ordering': ['-created_at', '-liked'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('zipcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('price', models.FloatField(default=0)),
                ('state', models.CharField(default='Delivered', max_length=30)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='myauth.myuser')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='back.order')),
            ],
            options={
                'ordering': ['-delivered_at', '-state'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('traited_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
